# Generated by Django 5.0.3 on 2024-04-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('prioridad', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=6)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En_curso', 'En curso'), ('Cerrado', 'Cerrado')], max_length=10)),
                ('nota', models.CharField(max_length=100, verbose_name='Nota')),
                ('carpeta', models.CharField(max_length=100, verbose_name='Carpeta')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centaurApp.chat')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centaurApp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centaurApp.usuario')),
                ('lista_tickets', models.ManyToManyField(to='centaurApp.ticket')),
                ('tareas', models.ManyToManyField(to='centaurApp.tarea')),
            ],
            bases=('centaurApp.usuario',),
        ),
    ]
