# Generated by Django 5.0.3 on 2024-04-13 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_ini',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='lista_tickets',
            field=models.ManyToManyField(blank=True, to='centaurApp.ticket'),
        ),
        migrations.AlterField(
            model_name='agente',
            name='tareas',
            field=models.ManyToManyField(blank=True, to='centaurApp.tarea'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='carpeta',
            field=models.CharField(blank=True, max_length=100, verbose_name='Carpeta'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='conversacion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='centaurApp.chat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nota',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nota'),
        ),
    ]
