# Generated by Django 4.2.11 on 2024-04-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solicitante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Solicitante'),
        ),
    ]
