# Generated by Django 5.0.3 on 2024-04-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0002_ticket_fecha_fin_ticket_fecha_ini_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='carpeta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Carpeta'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='conversacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='centaurApp.chat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='nota',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nota'),
        ),
    ]
