# Generated by Django 4.2.11 on 2024-05-02 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0003_campo_formulario_opcion_delete_form_campo_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('campo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centaurApp.campo')),
                ('texto', models.CharField(max_length=200)),
            ],
            bases=('centaurApp.campo',),
        ),
        migrations.RemoveField(
            model_name='campo',
            name='formulario',
        ),
        migrations.RemoveField(
            model_name='campo',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='opcion',
            name='campo',
        ),
        migrations.AddField(
            model_name='formulario',
            name='campos',
            field=models.ManyToManyField(blank=True, to='centaurApp.campo'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='descripcion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='valor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DropdownField',
            fields=[
                ('campo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='centaurApp.campo')),
                ('opciones', models.ManyToManyField(blank=True, to='centaurApp.opcion')),
            ],
            bases=('centaurApp.campo',),
        ),
    ]
