# Generated by Django 4.2.11 on 2024-05-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0004_textfield_remove_campo_formulario_remove_campo_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
