# Generated by Django 4.2.11 on 2024-05-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0005_campo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dropdownfield',
            name='opciones',
        ),
        migrations.AddField(
            model_name='dropdownfield',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='centaurApp.opcion'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='dropdown_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='centaurApp.dropdownfield'),
            preserve_default=False,
        ),
    ]
