# Generated by Django 4.2.11 on 2024-05-15 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0007_remove_textfield_campo_ptr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
