# Generated by Django 4.2.11 on 2024-05-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0009_formulario_categoria_formulario_oculto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='opciones',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='campos',
        ),
        migrations.AddField(
            model_name='campo',
            name='opciones',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='centaurApp.opcion'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='campos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='centaurApp.campo'),
        ),
    ]
