# Generated by Django 4.2.11 on 2024-05-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0010_remove_campo_opciones_remove_formulario_campos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campo',
            name='opciones',
        ),
        migrations.RemoveField(
            model_name='formulario',
            name='campos',
        ),
        migrations.AddField(
            model_name='campo',
            name='formulario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='centaurApp.formulario'),
        ),
        migrations.AddField(
            model_name='opcion',
            name='campo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='centaurApp.campo'),
        ),
    ]
