# Generated by Django 4.2.11 on 2024-05-20 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centaurApp', '0012_remove_campo_formulario_remove_opcion_campo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tarea',
            name='fecha_ini',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='hora_ini',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Agente',
        ),
    ]
