# Generated by Django 4.2.11 on 2024-05-20 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centaurApp', '0013_tarea_creador_tarea_fecha_ini_tarea_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
