# Generated by Django 4.2.11 on 2024-05-20 10:37

import centaurApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centaurApp', '0016_remove_tarea_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(default=centaurApp.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
