# Generated by Django 4.2.11 on 2024-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0017_tarea_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='creador',
            field=models.CharField(max_length=100, verbose_name='Creador'),
        ),
    ]
