# Generated by Django 4.2.11 on 2024-05-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0018_alter_tarea_creador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('valor', models.CharField(max_length=500, verbose_name='valor')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='contenido',
            field=models.ManyToManyField(blank=True, to='centaurApp.contenido'),
        ),
    ]
