# Generated by Django 4.2.11 on 2024-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0019_contenido_ticket_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('en_curso', 'En curso'), ('cerrado', 'Cerrado')], default='abierto', max_length=10),
        ),
    ]
