# Generated by Django 4.2.11 on 2024-05-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0020_alter_ticket_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='baja', max_length=6),
        ),
    ]
