# Generated by Django 4.2.11 on 2024-05-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centaurApp', '0021_alter_ticket_prioridad'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='encargado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Encargado'),
        ),
    ]
